---
title: "6 Compile data and explore"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### 1. Get Packages, set working directory, etc. 
```{r packages}
library(tidyverse)
library(rgdal)
library(sf)

# setwd("~/Projects/Organics/Working/organics_repo/Rmarkdown/")

```

#### 2. Read in data (shapefile) for each year, and turn into df to rbind in next chunk
```{r data}

years = 2013:2019

## Read in shapefiles and make into a simple data.frame without geometry
for(i in years){
  
  tmp = read_sf(paste0("../R_output/spatial/final_organics_data/",i,"/all_organics_pest_",i,".shp")) %>% 
    as.data.frame() %>% 
    dplyr::select(-geometry)
  
  assign(paste0("organics_df_",i),tmp)
  
  rm(tmp)
  
}

```

#### 3. Compile (rbind) years into one df
```{r compile_for_csv}

all_years_df <- data.frame(matrix(ncol=ncol(organics_df_2013),nrow=0))
colnames(all_years_df) <- colnames(organics_df_2013)

for(i in years){
  
  tmp <- eval(as.name(paste0("organics_df_",i)))
  
  all_years_df = rbind(all_years_df,tmp)
  
  remove(tmp)
  
}

# Check
table(all_years_df$year)
 
# colnames(all_years_df) = c("permitsite","permit","s_status","permittee","comm_original","comm_code","agroclass","genus","family",
#                            "comm_edit","acres","soil_quality","apn_org","trs_org","cdfa_org","KernComm_org","KernPermittee_org",
#                            "all_org","year","KgPestAI","KgPestPrd","KgAerialAI","GroundAI","OtherAI","KgAiWater","KgAiWildlife",
#                            "KgAiMammal","KgAiBirds","KgAiFish", "KgAiBees", "KgAiEndgSp", "KgAiAqSp",
#                            "KgAiGrndWat","KgAiDrift","KgAiReptAmph","acrestreated" ,
#                            "KgAInsectOnly","KgAHerbOnly","KgAFungOnly","AiInsFng","N_crops","hectares","KgAIperHE","KgPRDperHE") #old order

colnames(all_years_df) = c("permitsite","permit","s_status","permittee","comm_original","comm_code","agroclass","genus","family",
                           "comm_edit","acres","soil_quality","apn_org","trsOnly_org","trsPermittee_Org","cdfa_org","KernComm_org","KernPermittee_org",
                           "all_org","permit_pur","site_pur","year", "Fuzzy", "n_crops","hectares")



write_csv(all_years_df, "../R_output/CSV/compiled_organics1319.csv")
```

#### Do the same as above without removing geometry then compile into single shapefile
```{r compile_for_shp}

years = 2013:2019

## Read in shapefiles 
for(i in years){
  
  tmp = readOGR(paste0("../R_output/spatial/final_organics_data/",i,"/all_organics_pest_",i,".shp")) %>% 
    st_as_sf() 
  
  assign(paste0("organics_shp_",i),tmp)
  
  rm(tmp)
  
}


all_years_shp <- organics_shp_2013
years = 2014:2019

for(i in years){
  
  tmp <- eval(as.name(paste0("organics_shp_",i)))
  
  all_years_shp = rbind(all_years_shp,tmp)
  
  remove(tmp)
  
}

# Check
table(all_years_shp$year)
 
# colnames(all_years_shp) = c("permitsite","permit","s_status","permittee","comm_original","comm_code","agroclass","genus","family",
#                            "comm_edit","acres","soil_quality","apn_org","trs_org","cdfa_org","KernComm_org","KernPermittee_org",
#                            "all_org","year","KgPestAI","KgPestPrd","KgAerialAI","GroundAI","OtherAI","KgAiWater","KgAiWildlife","KgAiMammal",
#                         "KgAiBirds","KgAiFish", "KgAiBees", "KgAiEndgSp", "KgAiAqSp", "KgAiGrndWat","KgAiDrift","KgAiReptAmph","acrestreated" , 
#                         "KgAInsectOnly","KgAHerbOnly","KgAFungOnly","AiInsFng","N_crops","hectares","KgAIperHE","KgPRDperHE","geometry") #old

# colnames(all_years_shp) = c("permitsite","permit","s_status","permittee","comm_original","comm_code","agroclass","genus","family",
#                            "comm_edit","acres","soil_quality","apn_org","trs_org","cdfa_org","KernComm_org","KernPermittee_org",
#                            "all_org","year","KgPestAI","KgPestPrd", "KgAiWater","KgAiWildlife",
#                            "KgAiMammal","KgAiBirds","KgAiFish", "KgAiBees", "KgAiEndgSp", "KgAiAqSp",
#                            "KgAiGrndWat","KgAiDrift","KgAiReptAmph","acrestreated" ,
#                            "KgAInsectOnly","KgAHerbOnly","KgAFungOnly","N_crops","hectares","KgAIperHE","KgPRDperHE", "geometry")

colnames(all_years_shp) = c("permitsite","permit_ag","s_status","permittee","comm_original","comm_code","agroclass","genus","family",
                           "comm_edit","acres","soil_quality","apn_org","trs_only","trs_permitteeOrg","cdfa_org","KernComm_org","KernPermittee_org",
                           "all_org","permit_pur","site_pur","year","Fuzzy","n_crops","hectares", "geometry")

writeOGR(as(all_years_shp,"Spatial"),
         dsn = "../R_output/spatial/final_organics_data/all_years",
         layer = "all_years_organics",
         driver = "ESRI Shapefile",
         overwrite_layer = T)
```



#### 5. Visualize some data

Organics per year
```{r orgs_per_year}

org_fields_perYear = all_years_df %>% 
  group_by(year) %>% 
  summarise(cdfa_organics = sum(cdfa_org),
            all_organics = sum(all_org))

ggplot(org_fields_perYear, aes(x = as.factor(year), y = cdfa_organics, fill = as.factor(year)))+
  geom_col()+
  geom_label(aes(label = cdfa_organics))+
  theme_classic()

ggplot(org_fields_perYear,aes(x = as.factor(year),y = all_organics,fill = as.factor(year)))+
  geom_col()+
  geom_label(aes(label = all_organics))+
  theme_classic()
```

Field size (hectares)
```{r field_size}
mean_hectares = all_years_df %>% 
  group_by(year,cdfa_org) %>% 
  summarise(mean_hectares = round(mean(hectares),2))

ggplot(mean_hectares,aes(x = as.factor(cdfa_org),y = mean_hectares,fill=as.factor(cdfa_org)))+
  geom_col()+
  geom_label(aes(label = mean_hectares))+
  facet_wrap(~year)

```

Soil Quality
```{r soilQuality}

mean_hectares = all_years_df %>% 
  group_by(year,cdfa_org) %>% 
  summarise(mean_soilQ = round(mean(soil_quality, na.rm=T),2))

ggplot(mean_hectares,aes(x = as.factor(cdfa_org),y = mean_soilQ,fill=as.factor(cdfa_org)))+
  geom_col()+
  geom_label(aes(label = mean_soilQ))+
  facet_wrap(~year)
```



#### 6. Check out pesticide use data
```{r pesticide}
#Pesticide data removed from dta

# explore_pst_use = all_years_df %>% 
#   group_by(cdfa_org,year) %>% 
#   summarise(avg_kg_pest_ai = round(mean(KgPestAI),2), # should adjust this for number of fields
#             avg_kg_ai_perHec = round(mean(KgAIperHE),2))
# 
# ggplot(explore_pst_use,aes(x = as.factor(year), y = avg_kg_pest_ai, fill = as.factor(year)))+
#   geom_col()+
#   geom_label(aes(label = avg_kg_ai_perHec))+
#   facet_wrap(~cdfa_org)+
#   theme_classic()

```

