---
title: "Sofie-Map data and Crosswalk table"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Creating spatial dataset for map figures
```{r packages}
library(tidyverse)
library(rgdal)
library(sf)
library(haven)

#Reading in Ashley result dta to create shapefile for spatial maps for paper
mpdata = read_dta("../R_input/dta/organicAnalysisPUR.dta") %>% as.data.frame()
  
map_data <- mpdata %>% filter(year==2019) %>% dplyr::select(permitsite, year, hectares, soil_quality, comm_edit, comm_code2, KgPestAI, KgPestPrd)%>% dplyr::mutate(KgPestAIha=KgPestAI/hectares, KgPestPrdha=KgPestPrd/hectares) %>% dplyr::select(-KgPestAI, -KgPestPrd)

top15crops <- map_data %>% dplyr::select(permitsite, comm_code2) %>% group_by(comm_code2) %>% summarize(count=n()) %>% 
  arrange(-count) %>% dplyr::mutate(Order=1:nrow(.)) %>% ungroup() %>% 
  full_join(map_data, by="comm_code2") %>% dplyr::mutate(comm=tolower(ifelse(Order<=15, comm_edit, "Other")))%>% 
  dplyr::select(comm_edit, comm, comm_code2) %>% distinct() %>% 
  dplyr::mutate(comm=ifelse(comm_code2==29141, "grape", comm),
                comm=ifelse(comm_code2==2008, "tangerine", comm))
  #Make Grape and tangerine with same comm code have same comm edit

kernfields_2019<-read_sf("../R_input/spatial/kern_AG_shp/kern2019/kern2019.shp") %>% 
  dplyr::select(permitsite=PMT_SITE, P_STATUS, S_STATUS) %>% 
  dplyr::mutate(Location=as.character(geometry)) 
#There are: 1824 locations out of 11778 that have more than 1 entry (will be sumamrizing by)
  #Most rows is 42 (lots of organic multicrops)

joindf<-full_join(map_data, kernfields_2019, by="permitsite") %>% 
  full_join(top15crops, by=c("comm_edit", "comm_code2"))%>% 
  dplyr::mutate(comm=ifelse(S_STATUS=="M", "Multicrop", comm)) %>% 
    st_as_sf()

mapdf<-joindf %>% 
  group_by(Location) %>% 
  summarize(hectares=max(hectares, na.rm = TRUE),
            comm=names(which.max(table(comm))),
            soil_quality=max(soil_quality, na.rm=TRUE),
            KgPestPrdha=max(KgPestPrdha, na.rm=TRUE)) %>% 
  dplyr::mutate(soil_quality=ifelse(soil_quality==-Inf, NA, soil_quality)) %>% 
  dplyr::select(-Location)


write_sf(mapdf, "../R_output/spatial/map_data/mapdf.shp", delete_layer = TRUE)
```

#### Crosswalk table for yield gaps table to agroclass table
```{r}

#Crosswalk for yield gaps excel sheet
yieldclass<-mpdata %>% dplyr::select(agroclass) %>% distinct()
write_csv(yieldclass, "../R_output/CSV/yieldgapcrosswalk/agroclasses.csv")

```

