---
title: "Manuscript_Visualizations"
comm_adj: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### 1. Packages, data, and working directory
```{r get_packages_and_data}

library(tidyverse)
library(sf)
library(rgdal)
library(reshape2)
setwd("~/Desktop/Organics_Final/Working/R_files/Rmarkdown")

df = readOGR("../R_output/spatial/KernAg_CDFA_pest/2017/B50/KernAg_CDFA_Pest2017_B50.shp") %>%
  st_as_sf()
```

#### 2. Prepare dataframe for vis
```{r prep_vis_data}
    
# Separate the COMM column by '-' into COMM_x and COMM_y
comm_adj = df %>% 
  separate(col = "COMM", 
       into = c("COMM_x","COMM_y"), 
       sep = "-",
       remove = FALSE)

# Convert all COMM columns from factors to character strings
comm_adj$COMM=as.character(comm_adj$COMM)
comm_adj$COMM_x=as.character(comm_adj$COMM_x)
comm_adj$COMM_y=as.character(comm_adj$COMM_y)

# If the word 'ORGANIC' is in the COMM_y column, keep only the COMM_x column, 
# otherwise keep the original value in the COMM column
comm_adj$COMM_new <- ifelse(comm_adj$COMM_y == "ORGANIC"|is.na(comm_adj$COMM_y), comm_adj$COMM_x,comm_adj$COMM)

# Combine all lettuce categories into one
comm_adj$COMM_new <- ifelse(str_detect(comm_adj$COMM_new,"LETTUCE"),"LETTUCE",comm_adj$COMM_new)

# Remove the COMM_x and COMM_y columns
comm_adj = comm_adj %>% 
  dplyr::select(-COMM_x,-COMM_y)

# Replace NAs in the CDFA column with 0s
comm_adj$CDFA = ifelse(is.na(comm_adj$CDFA),0,1)

topCrops = comm_adj %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>%
  group_by(COMM_new) %>%
  summarise(total_orgFields = sum(CDFA)) %>% 
  arrange(-total_orgFields) %>%
  head(.,5)

top5_crops = topCrops$COMM_new


top5_O = comm_adj %>% 
  as.data.frame() %>% 
  filter(COMM_new %in% top5_crops) %>% 
  mutate(
    COMM_new = COMM,
    CDFA = CDFA,
    KgH_AI = KgPstAI/HE,
    KgH_mammal = KgAMmml/HE,
    KgH_birds = KgABrds/HE,
    KgH_bees = KgAiBes/HE,
    KgH_aqsp = KgAAqSp/HE,
    KgH_rep = KgARptA/HE
  ) %>% 
  dplyr::select(COMM,CDFA,KgH_AI,KgH_mammal,KgH_birds,KgH_bees,KgH_aqsp,KgH_rep,-geometry) %>% 
  melt(., id.vars = c("COMM","CDFA")) %>% 
  filter(CDFA == 1)

top5_C = comm_adj %>% 
  as.data.frame() %>% 
  filter(COMM_new %in% top5_crops) %>% 
  mutate(
    COMM = COMM_new,
    CDFA = CDFA,
    KgH_AI = KgPstAI/HE,
    KgH_mammal = KgAMmml/HE,
    KgH_birds = KgABrds/HE,
    KgH_bees = KgAiBes/HE,
    KgH_aqsp = KgAAqSp/HE,
    KgH_rep = KgARptA/HE
  ) %>% 
  dplyr::select(COMM,CDFA,KgH_AI,KgH_mammal,KgH_birds,KgH_bees,KgH_aqsp,KgH_rep,-geometry) %>% 
  melt(., id.vars = c("COMM","CDFA")) %>% 
  filter(CDFA == 0)

top5_all = comm_adj %>% 
  as.data.frame() %>% 
  filter(COMM_new %in% top5_crops) %>% 
  mutate(
    COMM = COMM_new,
    CDFA = CDFA,
    KgH_AI = KgPstAI/HE,
    KgH_mammal = KgAMmml/HE,
    KgH_birds = KgABrds/HE,
    KgH_bees = KgAiBes/HE,
    KgH_aqsp = KgAAqSp/HE,
    KgH_rep = KgARptA/HE
  ) %>% 
  dplyr::select(COMM,CDFA,KgH_AI,KgH_mammal,KgH_birds,KgH_bees,KgH_aqsp,KgH_rep,-geometry) %>% 
  melt(., id.vars = c("COMM","CDFA")) 
```


#### 2. Bar graph
```{r}

ggplot(top5_all, aes(x = COMM, y = mean(value))) +
  geom_col()+
  facet_wrap(~CDFA)

```

