---
title: "Soil Kriging"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Packages
```{r}
library(sf)
library(tidyverse)
library(sp)
library(gstat)
library(raster)
library(rgdal)
library(rspatial)
```

# Observed soil data (RASTER)
```{r}
# soil_ras <- raster("../R_output/spatial/SoilRaster/soil_ras.tif")
# soil_ras_270 <- raster::aggregate(soil_ras,6)
# 
# soil_ras_coords = as.data.frame(xyFromCell(soil_ras_270,1:ncell(soil_ras_270)))
# 
# soil_df = cbind(as.data.frame(soil_ras_270),soil_ras_coords) %>% 
#   filter(!is.na(soil_ras))
# 
# soil_sf = st_as_sf(soil_df, coords = c("x","y"))
# soil_sp = as_Spatial(soil_sf)
# plot(soil_sf, cex = .02)
# 840 not applicable for storie index
```

# Observed soil data (shapefile)
```{r}
options(digits = 20)

soil_centroid = read_sf("../R_input/spatial/KernSoilDataBasin/KernSoil_Subset.shp") %>% 
  filter(!(StorInd %in% c("NOT RATED","Not Applicable for Storie Index"))) %>% 
  st_centroid() 

soil_centroid$soil_value = ifelse(str_detect(soil_centroid$StorInd,"One"),1,
                                             ifelse(str_detect(soil_centroid$StorInd,"Two"),2,
                                                    ifelse(str_detect(soil_centroid$StorInd,"Three"),3,
                                                           ifelse(str_detect(soil_centroid$StorInd,"Four"),4,
                                                                  ifelse(str_detect(soil_centroid$StorInd,"Five"),5,
                                                                         ifelse(str_detect(soil_centroid$StorInd,"Six"),6,NA))))))

# Get coordinates from geometry column
soil_coords = data.frame(coords = as.character(soil_centroid$geometry))
soil_coords = separate(data = soil_coords, col = coords, into = c("x","y"),sep = ",")
soil_coords$x = str_sub(soil_coords$x,start = 3, end = nchar(soil_coords$x)) %>% 
  as.numeric()
soil_coords$y = str_sub(soil_coords$y,start = 1, end = nchar(soil_coords$y)-1) %>% 
  as.numeric()

soil_spdf = cbind(as.data.frame(soil_centroid),soil_coords)

soil_spdf = soil_spdf[which(!duplicated(soil_spdf[4:5])), ]

coordinates(soil_spdf) <- ~ x + y
crs(soil_spdf) <- crs(soil_sf)

# plot(soil_spdf)

ggplot(data = st_as_sf(soil_spdf))+
  geom_point(aes(x = x, y = y,color = as.factor(soil_value), size = soil_value), alpha = 0.5)

```

# Template raster
```{r}

soil_sf = read_sf("../R_input/spatial/KernSoilDataBasin/KernSoil_Subset.shp")
soil_r = raster(soil_sf)
res(soil_r) <- 5000
g = as(soil_r, "SpatialGrid")
plot(g)

```

# Fit variogram
```{r}

soil_gs = gstat(formula = soil_value ~ 1,
                 locations = soil_spdf)

soil_vgm <- variogram(soil_gs)
head(soil_vgm)
plot(soil_vgm)

## Fit the model
soil_fit = fit.variogram(soil_vgm,vgm(psill = 0.15, model = "Exp", range = 1.5, nugget = 0.01))
soil_fit

plot(variogramLine(soil_fit,20000), type = 'l')
points(soil_vgm[,2:3],pch=20,cex=0.1)

k = gstat(formula = soil_value~1,locations = soil_spdf, model = soil_fit)
k_predict = predict(k,g)
head(k_predict)
```

# Make the grid
```{r}
extent(soil_ras)

# Check to make sure observed value extent falls within larger extent
# plot(extent(soil_ras))
# plot(extent(soil_sp),add=T,col="red")

xnew = seq(-2149064,-1921184,length = (100))
ynew = seq(1689488,1529348,length = (100))
Grid = expand.grid(xnew,ynew)

colnames(Grid) <- c("xnew","ynew")
coordinates(Grid) <- ~ xnew + ynew
gridded(Grid) <- T
class(Grid)
plot(Grid)
```

# Develop variogram
```{r}

soil_vgm = variogram(soil_ras~1,data = soil_sp)
soil_fit = fit.variogram(soil_vgm, model = vgm(nugget = 1, psill = 6, range = 5, model = "Exp"))

soil_krige = krige(soil_ras ~ 1, soil_sp, newdata = Grid, model = soil_fit)
```

####
Trying inverse distance weighting
```{r}
soil_sf = read_sf("../R_input/spatial/KernSoilDataBasin/KernSoilData_QGISreproj.shp")
# soil_sf = read_sf("../R_input/spatial/KernSoilDataBasin/KernSoil_Subset.shp")

soil_ras = raster("../R_output/spatial/SoilRaster/soil_ras.tif")
soil_ras = crop(soil_ras, extent(soil_sf))
plot(soil_ras)

soil_points = as.data.frame(rasterToPoints(x = soil_ras))

coordinates(soil_points) <- ~ x + y
crs(soil_points) <- crs(soil_sf)

x_len = (xmax(soil_points) - xmin(soil_points))/269.5
y_len = (ymax(soil_points) - ymin(soil_points))/269.5

# To get 60m raster
xnew = seq(xmin(soil_points),xmax(soil_points),length = x_len)
ynew = seq(ymin(soil_points),ymax(soil_points),length = y_len)
Grid = expand.grid(xnew,ynew)

colnames(Grid) <- c("xnew","ynew")
coordinates(Grid) <- ~ xnew + ynew
gridded(Grid) <- T
fullgrid(Grid) <- T
class(Grid)
res(raster(Grid))
# plot(Grid)

proj4string(Grid) <- proj4string(soil_points)

### IDW
timestamp()
P.idw = gstat::idw(formula = soil_ras ~ 1, locations = soil_points, newdata = Grid, idp = 2, nmax = 50)
r = raster(P.idw)

r_mask <- mask(r,soil_sf)
writeRaster(r_mask,"../R_output/spatial/SoilRaster/soil_ras_IDW.tif", overwrite = T)


timestamp()
```


```{r}
### Cross validation 
cv_length = 500
random_sample = sample(x = 1:length(soil_points),size = cv_length, replace = F)

IDW.out <- vector(length = cv_length)
for (i in 1:length(random_sample)) {
  
  IDW.out[i] <- idw(soil_ras ~ 1, soil_points[-(random_sample[i]),], soil_points[random_sample[i],], idp=2)$var1.pred
  
  }

# sqrt(sum((IDW.out1.5 - soil_points$soil_ras[1:cv_length])^2)/cv_length)
sqrt(sum((IDW.out2 - soil_points$soil_ras[1:cv_length])^2)/cv_length) # 1.24 at coarse res
# sqrt(sum((IDW.out2.5 - soil_points$soil_ras[1:cv_length])^2)/cv_length)
# sqrt(sum((IDW.out3 - soil_points$soil_ras[1:cv_length])^2)/cv_length)

r = raster(P.idw2)
timestamp()

```

```{r}
## Selecting points randomly from polygons
soil_sf = read_sf("../R_input/spatial/KernSoilDataBasin/KernSoilData_QGISreproj.shp") %>%
  filter(!(StorInd %in% c("NOT RATED","Not Applicable for Storie Index")))

for(i in 1:nrow(soil_sf)){
  
  area = st_area(soil_sf[i,])
  n_pts = area/10000
  pts = sample(soil_sf[i,],n = n_pts, random)
}

```




